
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool: 'default'

variables:
  - name: CloudInitContent
  - name: resourceGroupName
    value: 'Emmanuel'
  - name: location
    value: 'Canada Central'
  - name: projectFolder
    value: 'AzureResourceGroup4'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = (Get-Content -Path 'C:\Users\Emmanuel\source\repos\AzureResourceGroup3\AzureResourceGroup3\cloud-Init.txt' -raw -Force)
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"

- script: |
    echo $(CloudInitContent)

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploying Azure KeyVAult
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Abonnement Azure 1(006ae760-9178-4c58-b965-89b732234df0)'
    subscriptionId: '006ae760-9178-4c58-b965-89b732234df0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Emmanuel'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\AzureResourceGroup3\AzureResourceGroup4\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\AzureResourceGroup3\AzureResourceGroup4\azuredeploy.parameters.json'
    overrideParameters: '-Secret EmmanuelMbatchou115'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'KeyVaultDeployment'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Abonnement Azure 1(006ae760-9178-4c58-b965-89b732234df0)'
    subscriptionId: '006ae760-9178-4c58-b965-89b732234df0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Emma'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/AzureResourceGroup3/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/AzureResourceGroup3/azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(vmadmin)'
    deploymentMode: 'Validation'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Abonnement Azure 1(006ae760-9178-4c58-b965-89b732234df0)'
    subscriptionId: '006ae760-9178-4c58-b965-89b732234df0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Emma'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/AzureResourceGroup3/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/AzureResourceGroup3/azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(vmadmin)'
    deploymentMode: 'Incremental'
    
  
- task: AzureKeyVault@2
  displayName: Get Secret
  inputs:
        azureSubscription: 'Abonnement Azure 1(006ae760-9178-4c58-b965-89b732234df0)'
        KeyVaultName: 'vmadmin'
        SecretsFilter: 'EmmanuelMbatchou115'
        RunAsPreJob: false
    
- task: PowerShell@2
  displayName: Test Secrets
  inputs:
        targetType: 'inline'
        script: |
              Write-Host $(vmadmin)

- task: AzurePowerShell@5
  displayName: Update Secret
  inputs:
        azureResourceManagerConnection: 'Abonnement Azure 1(006ae760-9178-4c58-b965-89b732234df0)'
        ScriptType: 'InlineScript'
        azurePowerShellVersion: 'LatestVersion'
        Inline: |
          # Set the variables
          $vaultName = "vmadmin"
          $secretName = "EmmanuelMbatchou115"
          $secretValue = "EmmanuelMbatchou215"
          
          # Update the secret value
          Set-AzKeyVaultSecret -VaultName $vaultName -Name $secretName -SecretValue (ConvertTo-SecureString $secretValue -AsPlainText -Force)


